services:
  backend:
    build:
      context: ./backend
    image: momo-backend:1.0
    restart: unless-stopped
    ports:
      - "8081:8081"
    secrets:
      - order_id_secret
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  frontend:
    build:
      context: ./frontend
    image: momo-frontend:1.0
    restart: unless-stopped
    ports:
      - "8088:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
secrets:
  order_id_secret:
    file: ./order_id_secret.txt